name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

  schedule:
    - cron: '0 16 * * 1'  # Build every monday, 16:00

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install
        run: |
          python --version
          pip install .

      - name: Test TL2022
        run: |
          python -m install_texlive -c="-a" -t 2022 -p $HOME/texlive -f tex-packages.txt -v 
          export PATH=$HOME/texlive/2022/bin/x86_64-linux:$PATH
          latexmk -lualatex -halt-on-error -interaction=nonstopmode hello.tex
          latexmk -c hello.tex

      - name: Test TL current
        run: |
          python -m install_texlive -c="-a" -p $HOME/texlive -v -f tex-packages.txt
          export PATH=$HOME/texlive/2025/bin/x86_64-linux:$PATH
          latexmk -lualatex -halt-on-error -interaction=nonstopmode hello.tex
